### ISSUE TITLE
rendy-resource errors while compiling

### ISSUE THREAD

**Issue by overjarko** [omni-viral/rendy#104]
Creating a new lib via cargo, adding rendy as dependency and building(with the nightly version) it gives me the following error while compiling rendy-resource: E0308

expected type `&<B as gfx_hal::Backend>::Device`
found type `&impl gfx_hal::Device<B>`

I am pretty new to rust and rendy, so it may just be a stupid mistake on my side.

**Comment by omni-viral** [comment]
It seems `rendy-memory 0.1.1` introduced breaking changes. Yanked. You can do `cargo update` and then build with `rendy-memory 0.1.0`

**Comment by omni-viral** [comment]
You can build with git dependency as well, there are plenty of changes so you would better not rewrite your code once 0.2 released.

**Comment by overjarko** [comment]
Updating to 0.1.0 worked. Great thanks for the fast respond!
