### ISSUE TITLE
[BUG] DynamicAllocator is not used

### ISSUE THREAD

**Issue by zakorgy** [omni-viral/rendy#84]
I have noticed that here is no dynamic allocation, because the [max_block_size](https://github.com/omni-viral/rendy/blob/master/memory/src/allocator/dynamic.rs#L218) function of `DynamicAllocator` always returns zero, since `self.sizes` is created as an empty `HashMap`. This `max_block_size` is used to decide if we want allocate using a `DynamicAllocator` [here](https://github.com/omni-viral/rendy/blob/master/memory/src/heaps.rs#L344), but this will be always false due to the returning zero value.

I tought adding the `max_block_size` limit from `DynamicConfig` as a field to the `DynamicAllocator` and using it in the above mentioned function would fix this, but now when I run the `quads` example there is a panic:
```
TRACE 2019-03-28T08:03:55Z: rendy_memory::allocator::dynamic: Allocate block. type: 1, size: 32000000
TRACE 2019-03-28T08:03:55Z: rendy_memory::allocator::dynamic: Allocate new chunk: size: 2048000000
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AllocationError(OutOfMemory(OutOfDeviceMemory))', src/libcore/result.rs:997:5

```
As I can see the following happens: We try to allocate with `DynamicAllocator` and creating a new chunk, but the size exceeds the `max_block_size` limit and we fallback to dedicated allocation. This allocation fails because we run out of memory.

I have lowered the `max_block_size` limit in [BasicHeapsConfigure](https://github.com/omni-viral/rendy/blob/c40d74a298c9d46658a0572e2af9f64b1dd1f432/factory/src/config.rs#L162) to 8 MB to see if we don't run out of memory. Now the quad example runs, and it tries to allocate with DynamicAllocator, but what really happens is [alloc_from_chunk](https://github.com/omni-viral/rendy/blob/c40d74a298c9d46658a0572e2af9f64b1dd1f432/memory/src/allocator/dynamic.rs#L302) and [alloc_chunk](https://github.com/omni-viral/rendy/blob/c40d74a298c9d46658a0572e2af9f64b1dd1f432/memory/src/allocator/dynamic.rs#L239) calls each other recursively until we reach the [max_block_size](https://github.com/omni-viral/rendy/blob/c40d74a298c9d46658a0572e2af9f64b1dd1f432/memory/src/allocator/dynamic.rs#L245) limit and we fallback to the dedicated memory allocation again. Here is a part of my trace log which demonstrates well the recursive calls, and the dedicated allocation in the end (`Map new memory object`).
```
TRACE 2019-03-28T08:27:58Z: rendy_memory::allocator::dynamic: Allocate block. type: 1, size: 512
TRACE 2019-03-28T08:27:58Z: rendy_memory::allocator::dynamic: Allocate new chunk: size: 32768
TRACE 2019-03-28T08:27:58Z: rendy_memory::allocator::dynamic: Allocate block. type: 1, size: 32768
TRACE 2019-03-28T08:27:58Z: rendy_memory::allocator::dynamic: Allocate new chunk: size: 2097152
TRACE 2019-03-28T08:27:58Z: rendy_memory::allocator::dynamic: Allocate block. type: 1, size: 2097152
TRACE 2019-03-28T08:27:58Z: rendy_memory::allocator::dynamic: Allocate new chunk: size: 134217728
TRACE 2019-03-28T08:27:58Z: rendy_memory::allocator::dynamic: Map new memory object
```

The full log is here : https://gist.github.com/zakorgy/fffa38cac7c9805484dd9d9a059c9646

**Comment by omni-viral** [comment]
This recursive allocation that ends in dedicated allocator is exactly expected behaviour

**Comment by omni-viral** [comment]
For not running out of memory it should limit how big largest chunk is.
If max block size is 32MB then it tries to allocate 2GB chunk which is too much. 256MB limit for chunk size can be reasonable default.
